kit:
  name: "nopCommerce Starter Kit"
  link: https://github.com/qubell-bazaar/nopCommerce-starter-kit
  applications:
    - name: "nopCommerce"
      manifest: https://raw.github.com/qubell-bazaar/nopCommerce-starter-kit/2.0-36p/nopCommerce-starter-kit.yml
    - name: "Database"
      manifest: https://raw.github.com/qubell-bazaar/component-mssql/2.0-36p/component-mssql.yml 
    - name: "Application Server"
      manifest: https://raw.github.com/qubell-bazaar/component-iis/2.0-36p/component-iis.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * Amazon EC2 or Rackspace CloudServers account;
        * Ports 22, 80, 1433. 3389 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
